### ISSUE TITLE
make PLAY_TINO Mobile

### ISSUE THREAD

**Issue by jzongyun** [DEV-TINO/PLAY-TINO-FE#44]
## Minji
- check 1 ~ 3

## Jeongyun
- check 4

## Todo
- [ ] check 1: Main Page
- [ ] check 2: Favorite Page
- [ ] check 3: Statistic table
- [x] check 4: Comment
